import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Navbar from "@/components/SheardComponents/Navbar/Navbar";
import Footer from "@/components/SheardComponents/Footer/Footer";





const inter = Roboto_Serif({ subsets: ["latin"], weight: ["100","300", "400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* head line start */}
      <head>
      <Script src="https://kit.fontawesome.com/816fadddff.js" crossorigin="anonymous"></Script>
      </head>
      {/* head line end */}
      <body className={inter.className}>

       <Navbar/>
        {children}
       <Footer/>
      </body>
    </html>
  );
}
